import os
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parents[2]
RUNTIME = Path(os.environ.get('HELPDESK_RUNTIME', BASE_DIR / 'runtime')).resolve()
SECRET_KEY = (RUNTIME / 'keys' / 'django.key').read_text().strip()
DATA_KEY_FILE = RUNTIME / 'keys' / 'data.key'
LOG_KEY_FILE = RUNTIME / 'journal' / 'journal.key'
DEBUG = False
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'testserver']
INSTALLED_APPS = ['django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'django.contrib.sites', 'django.contrib.humanize', 'portal.apps.PortalConfig', 'helpdesk', 'rest_framework']
MIDDLEWARE = ['django.middleware.security.SecurityMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'portal.middleware.ActorMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware', 'whitenoise.middleware.WhiteNoiseMiddleware']
ROOT_URLCONF = 'demodesk.config.urls'
AUTH_USER_MODEL = 'portal.User'
TEMPLATES = [{'BACKEND':'django.template.backends.django.DjangoTemplates', 'DIRS':[], 'APP_DIRS':True, 'OPTIONS': {'context_processors':['django.template.context_processors.request', 'django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages']}}]
DATABASES = {'default': {'ENGINE':'django.db.backends.sqlite3', 'NAME': RUNTIME / 'helpdesk.sqlite3', 'OPTIONS': {'timeout': 30}}}
PASSWORD_HASHERS = ['portal.hashers.PasswordHasher']
AUTH_PASSWORD_VALIDATORS = [{'NAME':'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length':12}}]
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/tickets/'
LOGOUT_REDIRECT_URL = '/login/'
SESSION_COOKIE_AGE = 3600
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_SSL_REDIRECT = False
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_HSTS_SECONDS = 0
SECURE_CONTENT_TYPE_NOSNIFF = True
DATA_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024
FILE_UPLOAD_HANDLERS = ['django.core.files.uploadhandler.MemoryFileUploadHandler']
STATIC_URL = '/static/'
STATIC_ROOT = RUNTIME / 'static'
MEDIA_ROOT = RUNTIME / 'media'
MEDIA_URL = '/media/'
STORAGES = {'default': {'BACKEND':'portal.storage.AttachmentStorage'}, 'staticfiles': {'BACKEND':'django.contrib.staticfiles.storage.StaticFilesStorage'}}
EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'
DEFAULT_FROM_EMAIL = 'support@example.test'
SITE_ID = 1
LANGUAGE_CODE = 'ru'
TIME_ZONE = 'Asia/Qyzylorda'
USE_TZ = True
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
HELPDESK_TEAMS_MODE_ENABLED = False
HELPDESK_ENABLE_PER_QUEUE_STAFF_PERMISSION = True
HELPDESK_ALLOW_NON_STAFF_TICKET_UPDATE = False
HELPDESK_VIEW_A_TICKET_PUBLIC = False
HELPDESK_SUBMIT_A_TICKET_PUBLIC = False
HELPDESK_API_ENABLED = False
HELPDESK_KB_ENABLED = True
HELPDESK_DEFAULT_SETTINGS = {'use_email_as_submitter': True, 'email_on_ticket_assign':False, 'email_on_ticket_change':False, 'login_view_ticketlist':True, 'tickets_per_page':25}
LOGGING = {'version':1, 'disable_existing_loggers':False, 'handlers': {'null':{'class':'logging.NullHandler'}}, 'loggers': {'django':{'handlers':['null'],'propagate':False}, 'waitress':{'handlers':['null'],'propagate':False}}}
